### ISSUE TITLE
 The containner is ping to any address

### ISSUE THREAD

**Issue by danielAlbuquerque** [monitoringartist/kubernetes-zabbix#1]
![screen shot 2016-10-02 at 23 50 53](https://cloud.githubusercontent.com/assets/6063722/19026351/2171dfda-88fb-11e6-8a96-5c59a52fe6c5.png)

**Comment by jangaraj** [comment]
What is expected behaviour?
How did you start/configure your containers and cluster?

**Comment by jangaraj** [comment]
Closing - no user response.
