### ISSUE TITLE
failed to accept an incoming connection from "kubernetes node x.x.x.x" rejected, allowed hosts: "zabbix-server.mycompany.com"

### ISSUE THREAD

**Issue by kkhamruddin-pk** [monitoringartist/kubernetes-zabbix#10]
failed to accept an incoming connection from "kubernetes node x.x.x.x" rejected, allowed hosts: "zabbix-server.mycompany.com"

- am getting the above error in zabbix agent logs
- MY zabbix-server is running as a kubernetes pod. And I have installed zabbix-agent package on a VM.... when zabbix server trying to fetch info from VM it is contacting the kubernetes node proxy and giving me the above error
- Is there any way that I can connect my non kubernetes instance to zabbix-server pod.?

**Comment by jangaraj** [comment]
Problem is only with your Zabbix configuration, which is not in the scope of this project. Please use https://www.zabbix.org/wiki/Getting_help
