### ISSUE TITLE
ErrImagePull  Error

### ISSUE THREAD

**Issue by OrwinLopes** [monitoringartist/kubernetes-zabbix#11]
I am new to kubernetes & trying your blog to run zabbix container on minkube. i am getting ImagePullBackOff Error 
Below describe error for pod :-
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  17m                  default-scheduler  Successfully assigned default/zabbix-web-786kd to minikube
  Warning  Failed     16m                  kubelet, minikube  Failed to pull image "monitoringartist/zabbix-xxl:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 34.201.236.93:443: connect: connection refused
  Warning  Failed     15m                  kubelet, minikube  Failed to pull image "monitoringartist/zabbix-xxl:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 100.24.246.89:443: connect: connection refused
  Normal   Pulling    14m (x4 over 17m)    kubelet, minikube  Pulling image "monitoringartist/zabbix-xxl:latest"
  Warning  Failed     14m (x4 over 16m)    kubelet, minikube  Error: ErrImagePull
  Warning  Failed     14m (x2 over 16m)    kubelet, minikube  Failed to pull image "monitoringartist/zabbix-xxl:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 34.206.236.31:443: connect: connection refused
  Warning  Failed     12m (x14 over 16m)   kubelet, minikube  Error: ImagePullBackOff
  Normal   BackOff    2m7s (x56 over 16m)  kubelet, minikube  Back-off pulling image "monitoringartist/zabbix-xxl:latest"

**Comment by jangaraj** [comment]
I didn't publish any blog about minikube. Try to use `monitoringartist/dockbix-xxl:latest` instead of `monitoringartist/zabbix-xxl:latest`

**Comment by OrwinLopes** [comment]
Thanks alot jangaraj for your quick reply !! i got my web & app pod running ...but DB still showing the same error..
