### ISSUE TITLE
Can zabbix-server in k8s obtain external IP of agents from separate GCE project ?

### ISSUE THREAD

**Issue by Blasterdick** [monitoringartist/kubernetes-zabbix#2]
From [this](https://github.com/kubernetes/kubernetes/issues/37483) issue you can see, that my zabbix-server can't get appropriate zabbix-agent external IP, which makes monitoring unusable. 

Can your kubernetes zabbix-server accept connections from outer world properly? And if so, how? 

Thanks in advance.

**Comment by jangaraj** [comment]
Could you visit IRC #zabbix please?
