### ISSUE TITLE
Issue of the zabbix agent configuration.

### ISSUE THREAD

**Issue by bg1szd** [monitoringartist/kubernetes-zabbix#3]
When configuring the zabbix agent, have to update the Server, ServerActive and Hostname fields in the /etc/zabbix/zabbix_agentd.conf file.  Here both Server and ServerActive is defined via the env variable.  How about the Hostname field? 
If there is other fields in the zabbix_agentd.conf to be updated, do I have to access the container as kubectl exec zabbix-agent -it /bin/sh  to edit the zabbix-agentd.conf manually?
Thanks!

**Comment by jangaraj** [comment]
Please read documentation of used Docker image first. There must be option how to configure it.
