### ISSUE TITLE
Pod metrics not collected

### ISSUE THREAD

**Issue by raul-barreto** [monitoringartist/kubernetes-zabbix#5]
Hi,

We installed the dockbix agent daemonset in our kubernetes cluster and it successfully connected the pod but the metrics aren't been collected. Is it a permission issue ? Do I need to create a custom role to the daemon set ?

**Comment by jangaraj** [comment]
More information is needed. What is installed and how is it configured, errors, logs, ...

**Comment by raul-barreto** [comment]
I installed the dockbix-agent-xxl-daemonset.yaml, just changing the ZA_Server and ZA_ServerActive environment variables; and I have installed the Zabbix Proxy from the image zabbix-proxy-sqlite3:latest.

The Zabbix Proxy and the agents communicate but when getting the containers metrics, it's show the followed error:

> 21148:20180711:160118.552 Cannot detect used docker driver
> 21148:20180711:160118.552 docker.up check is not available at the moment - no cpu_cgroup directory
> 21148:20180711:160118.552 Sending back [ZBX_NOTSUPPORTED: docker.up check is not available at the moment - no cpu_cgroup directory]
> ...
> 21148:20180711:160118.555 Requested [docker.mem[/k8s_POD_dockbix-agent-xxl-7n5dp_zabbix_049bdb68-8516-11e8-9bc3-1214ebe58624_0,total_rss]] 
> 21148:20180711:160118.555 Metric source file: /rootfs/sys/fs/cgroup/memory/78236f3d4917ae0d0b967e973c311941eb716963a773a1283e11fe2c3d932235/memory.stat
> 21148:20180711:160118.555 Cannot open metric file: '/rootfs/sys/fs/cgroup/memory/78236f3d4917ae0d0b967e973c311941eb716963a773a1283e11fe2c3d932235/memory.stat'
> 21148:20180711:160118.556 Sending back [ZBX_NOTSUPPORTED: Cannot open memory.stat file]

**Comment by raul-barreto** [comment]
I am using Amazon Linux instances with the Kubernetes.

**Comment by jangaraj** [comment]
It's not an issue of this project. I guess, it's already reported issue https://github.com/monitoringartist/zabbix-docker-monitoring/issues.
