### ISSUE TITLE
Cannot access any menus in Zabbix

### ISSUE THREAD

**Issue by tsunamireversal-zz** [monitoringartist/kubernetes-zabbix#8]
When clicking any menu other than the default one in Zabbix main menu, I see (in the F12 console menu):

Uncaught ReferenceError: MMenu is not defined
    at HTMLLIElement.onclick (dashconf.php:33)

Reproduced with Firefox, Chrome, Vivaldi, IE, Edge

**Comment by jangaraj** [comment]
It looks like a problem with nginx without clean root cause. See:
- https://github.com/monitoringartist/dockbix-xxl/issues/111
- https://www.zabbix.com/forum/zabbix-help/358511-zabbix-3-4-web-frontend-on-alpine-linux-top-menu-items-don-t-work

**Comment by hellowenqi** [comment]
i solve the problem by doing the following:

1. kubectl logs zabbix-web-mbtds
`
2019/06/12 05:29:50 [crit] 501#0: *269 open() "/var/lib/nginx/tmp/fastcgi/4/06/0000000064" failed (13: Permission denied) while reading upstream, client: 10.244.2.0, server: , request: "GET /jsLoader.php?ver=3.2.7%20(2018-04-13)%20XXL&lang=zh_CN&showGuiMessaging=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-www.sock:", host: "k8w2:30739"
`

2. chown of /var/lib/nginx  and its children
`chown -R www:www /var/lib/nginx`
